export const imageDict = {
  Ac: "/images/01_Ace_Clubs_100.png",
  Ad: "/images/01_Ace_Diamonds.png",

  Ah: "/images/01_Ace_Hearts.png",
  As: "/images/01_Ace_Spades.png",
  "2c": "/images/02_Clubs.png",
  "2d": "/images/02_Diamonds.png",
  "2h": "/images/02_Hearts.png",
  "2s": "/images/02_Spades.png",
  "3c": "/images/03_Clubs.png",
  "3d": "/images/03_Diamonds.png",
  "3h": "/images/03_Hearts.png",
  "3s": "/images/03_Spades.png",
  "4c": "/images/04_Clubs.png",
  "4d": "/images/04_Diamonds.png",
  "4h": "/images/04_Hearts.png",
  "4s": "/images/04_Spades.png",
  "5c": "/images/05_Clubs.png",
  "5d": "/images/05_Diamonds.png",
  "5h": "/images/05_Hearts.png",
  "5s": "/images/05_Spades.png",
  "6c": "/images/06_Clubs.png",
  "6d": "/images/06_Diamonds.png",
  "6h": "/images/06_Hearts.png",
  "6s": "/images/06_Spades.png",
  "7c": "/images/07_Clubs.png",
  "7d": "/images/07_Diamonds.png",
  "7h": "/images/07_Hearts.png",
  "7s": "/images/07_Spades.png",
  "8c": "/images/08_Clubs.png",
  "8d": "/images/08_Diamonds.png",
  "8h": "/images/08_Hearts.png",
  "8s": "/images/08_Spades.png",
  "9c": "/images/09_Clubs.png",
  "9d": "/images/09_Diamonds.png",
  "9h": "/images/09_Hearts.png",
  "9s": "/images/09_Spades.png",
  Tc: "/images/10_Clubs.png",
  Td: "/images/10_Diamonds.png",
  Th: "/images/10_Hearts.png",
  Ts: "/images/10_Spades.png",
  Jc: "/images/11_Jack_Clubs.png",

  Jd: "/images/11_Jack_Diamonds.png",

  Jh: "/images/11_Jack_Hearts.png",

  Js: "/images/11_Jack_Spades.png",

  Qc: "/images/12_Queen_Clubs.png",
  Qd: "/images/12_Queen_Diamonds.png",
  Qh: "/images/12_Queen_Hearts.png",
  Qs: "/images/12_Queen_Spades.png",
  Kc: "/images/13_King_Clubs.png",
  Kd: "/images/13_King_Diamonds.png",
  Kh: "/images/13_King_Hearts.png",
  Ks: "/images/13_King_Spades.png",
  Back: "/images/skull_Card_back.png"
};
